# Site settings
baseurl = "http://mdmmarketing.com.au"
languageCode = "en-us"
title = "Martin Dench"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Martin Dench"
	description = "MDM Consultancy"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "alex.m.walker@gmail.com"
	# email = "martin@mdmmarketing.com.au"

    # Link custom assets relative to /static
    # custom_css = ['css/carousel.css']
		custom_css = [ "css/carousel.css", "css/extra.css"]
		# custom_css = ['css/extra.css']
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "MDM Consulting"
		services = "Services"
		about = "About"
		portfolio = "Portfolio"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    #[[menu.postpend]]
    #    url = "http://gohugo.io"
    #    name = "External link"
    #    weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "I'm Martin Dench"
		subtitle = "How can I help?"
		buttonText = "Let's talk"
		blurb1 = "At MDM Consulting, we're all about looking at things differently. We love hunting for the missed opportunities. We love sniffing out the cost-effective wins. We love finding the hidden markets."
 		blurb2 = "It might be a simple tweak to an existing program that begins with <em>“What if we…?”</em>. Or it could be a completely new program for the next evolution of your business."
 		blurb3 = "Our experience, in conjunction with an extensive information gathering and research component, lets us provide a detailed overview of your challenges before delivering a comprehensive roadmap on how to move forward."
 		blurb4 = "Having worked with some of the world’s leading brands – Bosch, King Gee, Hard Yakka and the Western Bulldogs – I am perfectly positioned to tackle any challenge you have and become a key strategic partner to your business."

  # Carousel section
  [params.carousel]
      enable = true
      title = "Carousel"
      subtitle = "carousel subtitle"

      [[params.carousel.row]]

        [[params.carousel.row.list]]
        title = "Western Bulldogs"
        description = " As General Manager of Commercial Operations I was responsible for generating $10m in revenue with key achievements being selling the naming rights to Whitten Oval and renewing major sponsors to club record dollars and tenure"


  # Carousel section
  [params.martin]
      enable = false
      title = "martin"
      subtitle = "martin"
      # description = "I started MDM Consulting after 20 years, and have worked on some of the world’s leading brands.  I have extensive experience across the full marketing mix, particularly in branding, marketing strategy development, sponsorship and events.
# My ability to identify and solve problems quickly and tackle complex situations methodically ensures I can provide focused, independent recommendations to my clients."

	# Services section
	[params.services]
    enable = true
		title = "Services"
		subtitle = "MDM Marketing offers a range of services including:"
		blurb = "I will challenge what you know about your business and the markets you operate in. I might even confirm you know your stuff! Ultimately I will provide a new perspective through a fresh set of eyes on the challenges your business is facing and importantly provide solutions"

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-bullseye"
                title = "Strategy"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-bullhorn"
                title = "Marketing"
                description = "Stuff ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

            [[params.services.row.list]]
                icon = "fa-map-o"
                title = "Planning"
                description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

				    [[params.services.row.list]]
				        icon = "fa-balance-scale"
				        title = "Review"
				        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

		        [[params.services.row.list]]
			          icon = "fa-thumbs-o-up"
	              title = "Sponsorship"
	              description = "Stuff ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

			      [[params.services.row.list]]
	              icon = "fa-diamond"
		            title = "Branding"
			          description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."


	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Success Stories"

		[params.portfolio.modal]
            client = "Western Bulldogs"
            date = "2015"
            category = "Sport & Recreation"
            buttonText = "Close project"




    # About section
	[params.about]
    enable = false
		title = "About"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2011"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2011"
			title = "An Agency is Born"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2012"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "4.jpg"
			date = "July 2014"
			title = "Phase Two Expansion"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
        enable = false
		title = "Our amazing team"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Kay Garland"
			position = "Lead Designer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "2.jpg"
			name = "Larry Parker"
			position = "Lead Marketer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "3.jpg"
			name = "Diana Pertersen"
			position = "Lead Developer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Client section
    [params.clients_list]
        enable = true

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "efm.jpg"
    		link = "http://www.efmlogistics.com.au/"

    	[[params.clients]]
    		logo = "swisse.jpg"
    		link = "https://www.swisse.com/en-au/home"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact us"
		subtitle  = "It starts with a quick chat. Let's look at opportunities"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
    enable = true
		copyright = "Published under the Apache License 2.0."

		#[[params.footer.social]]
		#	icon = "fa-twitter"
		#	link = "#"

		#[[params.footer.social]]
		#	icon = "fa-facebook"
		#	link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/in/martin-dench-91523436"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
